# streamlit_app.py
import streamlit as st
from data_loader import load_dataset_paths, get_bird_classes
from model import initialize_model, predict_bird_species

# Configures the application window browser properties
st.set_page_config(page_title="Bird 20-Species Identifier", page_icon="🐦", layout="centered")

st.title("🐦 Bird 20-Species Classification System")
st.write("This app uses a machine learning architecture to recognize and classify bird species dynamically.")

# --- STEP 1: Process and download dataset components asynchronously ---
@st.cache_resource
def setup_runtime_components():
    # Cache dataset downloads so it doesn't trigger on every button click
    paths = load_dataset_paths()
    classes = get_bird_classes(paths["train"])
    model = initialize_model(num_classes=len(classes))
    return classes, model

with st.spinner("Initializing system and checking Kaggle requirements..."):
    class_labels, trained_model = setup_runtime_components()

# --- STEP 2: Render Frontend Elements ---
st.write("### Try It Out")
uploaded_file = st.file_uploader("Upload an image of a bird (JPG/PNG formats)...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Divide the UI space into two columns (Left: Preview, Right: Inference Analytics)
    col1, col2 = st.columns(2)
    
    with col1:
        st.image(uploaded_file, caption="Uploaded Target", use_column_width=True)
        
    with col2:
        st.write("#### Analytics Engine Results:")
        with st.spinner("Processing visual matrices..."):
            # Execute inference
            label, score = predict_bird_species(uploaded_file, trained_model, class_labels)
        
        # Display results cleanly
        st.metric(label="Predicted Species", value=label.title())
        st.metric(label="Confidence Score", value=f"{score * 100:.2f}%")
        
        # UI alert banner logic depending on certainty metrics
        if score > 0.70:
            st.success("High match assurance generated by neural network logic.")
        else:
            st.warning("Low confidence score. Please double-check if the target falls within the 20 target domains.")

# --- SIDEBAR DISPLAY ---
st.sidebar.markdown("### Supported Species Ecosystem")
st.sidebar.write(f"The model is capable of indexing **{len(class_labels)} unique species variants**:")
for item in class_labels:
    st.sidebar.markdown(f"- {item.title()}")